import { StringKeySchema, Type, type Static, type TSchema } from './schema.js';
import { ApplicationSchema, CreateApplicationInputSchema, ApiResourceSchema, CreateResourceInputSchema, ScopeSchema, ConnectorSchema, OrganizationSchema, OrganizationMemberSchema, RoleSchema, PermissionSchema, SignInExperienceSchema, ApplicationSignInExperienceSchema, EffectiveSignInExperienceSchema, PublicEffectiveSignInExperienceSchema, PublicPhraseBundleSchema, AuditLogEntrySchema, WebhookSchema, CapabilitiesResponseSchema, CompatibilityCheckResultSchema } from './core.js';
import * as M from './sdk-models.js';

export type SdkHttpMethod = 'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE';
export interface SdkEndpoint<I extends TSchema = TSchema, R extends TSchema = TSchema> { method: SdkHttpMethod; path: string; input: I; result: R; responseKind: 'json' | 'void' | 'blob'; wireResult?: TSchema; }
const endpoint = <I extends TSchema, R extends TSchema, K extends SdkEndpoint['responseKind'], M extends SdkHttpMethod, P extends string>(method: M, path: P, input: I, result: R, responseKind: K) => ({ method, path, input, result, responseKind });

export const sdkEndpoints = {
  health: endpoint('GET', '/v1/health', Type.Object({  }), M.HealthSchema, 'json'),
  getProject: endpoint('GET', '/v1/project', Type.Object({  }), M.ProjectResponseSchema, 'json'),
  getCapabilities: endpoint('GET', '/v1/capabilities', Type.Object({  }), CapabilitiesResponseSchema, 'json'),
  getRuntimeHealth: endpoint('GET', '/v1/runtime/health', Type.Object({  }), M.RuntimeHealthSchema, 'json'),
  getOAuthServerStatus: endpoint('GET', '/v1/runtime/oauth-server', Type.Object({  }), M.OAuthServerStatusSchema, 'json'),
  getDiscovery: endpoint('GET', '/v1/runtime/discovery', Type.Object({  }), M.DiscoverySchema, 'json'),
  getJWKS: endpoint('GET', '/v1/runtime/jwks', Type.Object({  }), M.JWKSSchema, 'json'),
  listApplications: endpoint('GET', '/v1/applications', Type.Object({  }), M.ListResponseSchema(M.OAuthApplicationSchema), 'json'),
  createApplication: endpoint('POST', '/v1/applications', Type.Object({ body: M.CreateOAuthApplicationInputSchema }), M.OAuthApplicationSchema, 'json'),
  getApplication: endpoint('GET', '/v1/applications/:appId', Type.Object({ params: Type.Object({ appId: Type.String() }) }), M.OAuthApplicationSchema, 'json'),
  updateApplication: endpoint('PUT', '/v1/applications/:appId', Type.Object({ params: Type.Object({ appId: Type.String() }), body: M.UpdateOAuthApplicationInputSchema }), M.OAuthApplicationSchema, 'json'),
  deleteApplication: endpoint('DELETE', '/v1/applications/:appId', Type.Object({ params: Type.Object({ appId: Type.String() }) }), Type.Void(), 'void'),
  rotateApplicationSecret: endpoint('POST', '/v1/applications/:appId/rotate-secret', Type.Object({ params: Type.Object({ appId: Type.String() }) }), M.RotatedApplicationSecretSchema, 'json'),
  getApplicationConsentSettings: endpoint('GET', '/v1/applications/:appId/consent', Type.Object({ params: Type.Object({ appId: Type.String() }) }), M.ApplicationConsentSettingsSchema, 'json'),
  updateApplicationConsentSettings: endpoint('PUT', '/v1/applications/:appId/consent', Type.Object({ params: Type.Object({ appId: Type.String() }), body: M.ApplicationConsentInputSchema }), M.ApplicationConsentSettingsSchema, 'json'),
  getApplicationSignInExperience: endpoint('GET', '/v1/applications/:appId/sign-in-experience', Type.Object({ params: Type.Object({ appId: Type.String() }) }), ApplicationSignInExperienceSchema, 'json'),
  updateApplicationSignInExperience: endpoint('PUT', '/v1/applications/:appId/sign-in-experience', Type.Object({ params: Type.Object({ appId: Type.String() }), body: M.ApplicationSignInExperienceInputSchema }), ApplicationSignInExperienceSchema, 'json'),
  deleteApplicationSignInExperience: endpoint('DELETE', '/v1/applications/:appId/sign-in-experience', Type.Object({ params: Type.Object({ appId: Type.String() }) }), Type.Void(), 'void'),
  listApplicationBindings: endpoint('GET', '/v1/applications/:appId/bindings', Type.Object({ params: Type.Object({ appId: Type.String() }) }), M.ListResponseSchema(M.ApplicationBindingSchema), 'json'),
  createApplicationBinding: endpoint('POST', '/v1/applications/:appId/bindings', Type.Object({ params: Type.Object({ appId: Type.String() }), body: Type.Object({ resource_id: Type.String(), scope_id: Type.Optional(Type.String()) }) }), M.ApplicationBindingSchema, 'json'),
  deleteApplicationBinding: endpoint('DELETE', '/v1/applications/:appId/bindings/:bindingId', Type.Object({ params: Type.Object({ appId: Type.String(), bindingId: Type.String() }) }), Type.Void(), 'void'),
  listApplicationScopes: endpoint('GET', '/v1/applications/:appId/scopes', Type.Object({ params: Type.Object({ appId: Type.String() }) }), M.ListResponseSchema(M.ApplicationScopeSchema), 'json'),
  listApplicationRoles: endpoint('GET', '/v1/applications/:appId/roles', Type.Object({ params: Type.Object({ appId: Type.String() }) }), M.ListResponseSchema(M.RoleAssignmentSchema), 'json'),
  listApplicationLogs: endpoint('GET', '/v1/applications/:appId/logs', Type.Object({ params: Type.Object({ appId: Type.String() }), query: Type.Optional(Type.Object({ limit: Type.Optional(Type.Number()), cursor: Type.Optional(Type.String()) })) }), M.CursorListResponseSchema(M.WireAuditLogEntrySchema), 'json'),
  listApplicationOrganizations: endpoint('GET', '/v1/applications/:appId/organizations', Type.Object({ params: Type.Object({ appId: Type.String() }) }), M.ListResponseSchema(M.WireOrganizationSchema), 'json'),
  getApplicationAccessControl: endpoint('GET', '/v1/applications/:appId/access-control', Type.Object({ params: Type.Object({ appId: Type.String() }) }), M.ApplicationConsentSettingsSchema, 'json'),
  updateApplicationAccessControl: endpoint('PUT', '/v1/applications/:appId/access-control', Type.Object({ params: Type.Object({ appId: Type.String() }), body: M.ApplicationConsentInputSchema }), M.ApplicationConsentSettingsSchema, 'json'),
  listConnectors: endpoint('GET', '/v1/connectors', Type.Object({  }), M.ListResponseSchema(M.ProviderSchema), 'json'),
  getConnector: endpoint('GET', '/v1/connectors/:connectorId', Type.Object({ params: Type.Object({ connectorId: Type.String() }) }), M.ProviderSchema, 'json'),
  updateConnector: endpoint('PATCH', '/v1/connectors/:connectorId', Type.Object({ params: Type.Object({ connectorId: Type.String() }), body: M.UpdateConnectorInputSchema }), M.ProviderSchema, 'json'),
  testConnector: endpoint('POST', '/v1/connectors/:connectorId/test', Type.Object({ params: Type.Object({ connectorId: Type.String() }) }), M.ConnectorPreflightSchema, 'json'),
  getConnectorAuthorizationUri: endpoint('GET', '/v1/connectors/:connectorId/authorization-uri', Type.Object({ params: Type.Object({ connectorId: Type.String() }), query: Type.Optional(Type.Object({ redirect_uri: Type.Optional(Type.String()), state: Type.Optional(Type.String()), scope: Type.Optional(Type.String()) })) }), M.ConnectorAuthorizationSchema, 'json'),
  listConnectorFactories: endpoint('GET', '/v1/connectors/factories', Type.Object({ query: Type.Optional(Type.Object({ category: Type.Optional(Type.String()) })) }), M.ListResponseSchema(M.ConnectorFactorySchema), 'json'),
  upsertConnectorFactory: endpoint('PUT', '/v1/connectors/factories/:factoryId', Type.Object({ params: Type.Object({ factoryId: Type.String() }), body: Type.Object({ name: Type.String(), protocol: Type.String(), category: Type.String(), config_schema: Type.Optional(Type.Union([M.JsonObjectSchema, Type.Null()])), enabled: Type.Optional(Type.Union([Type.Boolean(), Type.Null()])) }) }), M.ConnectorFactorySchema, 'json'),
  listResources: endpoint('GET', '/v1/resources', Type.Object({  }), M.ListResponseSchema(M.WireResourceSchema), 'json'),
  createResource: endpoint('POST', '/v1/resources', Type.Object({ body: CreateResourceInputSchema }), M.WireResourceSchema, 'json'),
  getResource: endpoint('GET', '/v1/resources/:resourceId', Type.Object({ params: Type.Object({ resourceId: Type.String() }) }), M.WireResourceSchema, 'json'),
  updateResource: endpoint('PUT', '/v1/resources/:resourceId', Type.Object({ params: Type.Object({ resourceId: Type.String() }), body: Type.Optional(Type.Partial(CreateResourceInputSchema)) }), M.UpdatedResourceSchema, 'json'),
  deleteResource: endpoint('DELETE', '/v1/resources/:resourceId', Type.Object({ params: Type.Object({ resourceId: Type.String() }) }), Type.Void(), 'void'),
  addScope: endpoint('POST', '/v1/resources/:resourceId/scopes', Type.Object({ params: Type.Object({ resourceId: Type.String() }), body: Type.Omit(ScopeSchema, ['id', 'resource_id']) }), M.WireScopeSchema, 'json'),
  updateScope: endpoint('PUT', '/v1/resources/:resourceId/scopes/:scopeId', Type.Object({ params: Type.Object({ resourceId: Type.String(), scopeId: Type.String() }), body: Type.Partial(Type.Omit(ScopeSchema, ['id', 'resource_id'])) }), M.WireScopeSchema, 'json'),
  removeScope: endpoint('DELETE', '/v1/resources/:resourceId/scopes/:scopeId', Type.Object({ params: Type.Object({ resourceId: Type.String(), scopeId: Type.String() }) }), Type.Void(), 'void'),
  listResourceApplications: endpoint('GET', '/v1/resources/:resourceId/applications', Type.Object({ params: Type.Object({ resourceId: Type.String() }) }), M.ListResponseSchema(M.ApplicationBindingSchema), 'json'),
  listUsers: endpoint('GET', '/v1/users', Type.Object({ query: Type.Optional(Type.Object({ page: Type.Optional(Type.Number()), limit: Type.Optional(Type.Number()), search: Type.Optional(Type.String()), email: Type.Optional(Type.String()) })) }), M.ListResponseSchema(M.UserSchema), 'json'),
  createUser: endpoint('POST', '/v1/users', Type.Object({ body: Type.Object({ email: Type.Optional(Type.String()), phone: Type.Optional(Type.String()), password: Type.Optional(Type.String()), email_confirm: Type.Optional(Type.Boolean()), phone_confirm: Type.Optional(Type.Boolean()), user_metadata: Type.Optional(M.JsonObjectSchema) }) }), M.UserSchema, 'json'),
  getUser: endpoint('GET', '/v1/users/:userId', Type.Object({ params: Type.Object({ userId: Type.String() }) }), M.UserSchema, 'json'),
  updateUser: endpoint('PUT', '/v1/users/:userId', Type.Object({ params: Type.Object({ userId: Type.String() }), body: M.UpdateUserInputSchema }), M.UserSchema, 'json'),
  suspendUser: endpoint('POST', '/v1/users/:userId/suspend', Type.Object({ params: Type.Object({ userId: Type.String() }), body: Type.Optional(M.SuspendUserInputSchema) }), M.UserSchema, 'json'),
  deleteUser: endpoint('DELETE', '/v1/users/:userId', Type.Object({ params: Type.Object({ userId: Type.String() }) }), Type.Void(), 'void'),
  resetUserMfa: endpoint('POST', '/v1/users/:userId/mfa/:factorId/reset', Type.Object({ params: Type.Object({ userId: Type.String(), factorId: Type.String() }) }), M.MfaResetSchema, 'json'),
  listUserLogs: endpoint('GET', '/v1/users/:userId/logs', Type.Object({ params: Type.Object({ userId: Type.String() }), query: Type.Optional(Type.Object({ limit: Type.Optional(Type.Number()), cursor: Type.Optional(Type.String()) })) }), M.CursorListResponseSchema(M.WireAuditLogEntrySchema), 'json'),
  listUserOrganizations: endpoint('GET', '/v1/users/:userId/organizations', Type.Object({ params: Type.Object({ userId: Type.String() }) }), M.ListResponseSchema(M.WireOrganizationSchema), 'json'),
  getUserPermissions: endpoint('GET', '/v1/users/:userId/permissions', Type.Object({ params: Type.Object({ userId: Type.String() }), query: Type.Optional(Type.Object({ org_id: Type.Optional(Type.String()), application_id: Type.Optional(Type.String()) })) }), M.UserPermissionsSchema, 'json'),
  getUserRoles: endpoint('GET', '/v1/users/:userId/roles', Type.Object({ params: Type.Object({ userId: Type.String() }), query: Type.Optional(Type.Object({ application_id: Type.Optional(Type.String()) })) }), M.ListResponseSchema(M.RoleAssignmentSchema), 'json'),
  listOrganizations: endpoint('GET', '/v1/organizations', Type.Object({ query: Type.Optional(Type.Object({ page: Type.Optional(Type.Number()), limit: Type.Optional(Type.Number()), search: Type.Optional(Type.String()), application_id: Type.Optional(Type.String()) })) }), M.ListResponseSchema(M.WireOrganizationSchema), 'json'),
  createOrganization: endpoint('POST', '/v1/organizations', Type.Object({ body: Type.Object({ name: Type.String(), description: Type.Optional(Type.String()) }) }), M.WireOrganizationSchema, 'json'),
  getOrganization: endpoint('GET', '/v1/organizations/:orgId', Type.Object({ params: Type.Object({ orgId: Type.String() }) }), M.WireOrganizationSchema, 'json'),
  updateOrganization: endpoint('PUT', '/v1/organizations/:orgId', Type.Object({ params: Type.Object({ orgId: Type.String() }), body: Type.Object({ name: Type.Optional(Type.String()), description: Type.Optional(Type.String()) }) }), M.WireOrganizationSchema, 'json'),
  deleteOrganization: { ...endpoint('DELETE', '/v1/organizations/:orgId', Type.Object({ params: Type.Object({ orgId: Type.String() }) }), Type.Void(), 'void'), wireResult: M.DeletedOrganizationSchema },
  addOrganizationMember: endpoint('POST', '/v1/organizations/:orgId/members', Type.Object({ params: Type.Object({ orgId: Type.String() }), body: Type.Object({ user_id: Type.String(), role: Type.Optional(Type.String()) }) }), M.WireOrganizationMemberSchema, 'json'),
  listOrganizationMembers: endpoint('GET', '/v1/organizations/:orgId/members', Type.Object({ params: Type.Object({ orgId: Type.String() }), query: Type.Optional(Type.Object({ page: Type.Optional(Type.Number()), limit: Type.Optional(Type.Number()), search: Type.Optional(Type.String()) })) }), M.ListResponseSchema(M.WireOrganizationMemberSchema), 'json'),
  removeOrganizationMember: { ...endpoint('DELETE', '/v1/organizations/:orgId/members/:userId', Type.Object({ params: Type.Object({ orgId: Type.String(), userId: Type.String() }) }), Type.Void(), 'void'), wireResult: M.RemovedOrganizationMemberSchema },
  updateOrganizationMemberRole: endpoint('PATCH', '/v1/organizations/:orgId/members/:userId', Type.Object({ params: Type.Object({ orgId: Type.String(), userId: Type.String() }), body: Type.Object({ role: Type.String() }) }), M.WireOrganizationMemberSchema, 'json'),
  listOrganizationInvitations: endpoint('GET', '/v1/organizations/:orgId/invitations', Type.Object({ params: Type.Object({ orgId: Type.String() }) }), M.ListResponseSchema(M.OrganizationInvitationSchema), 'json'),
  createOrganizationInvitation: endpoint('POST', '/v1/organizations/:orgId/invitations', Type.Object({ params: Type.Object({ orgId: Type.String() }), body: Type.Object({ email: Type.String(), role: Type.Optional(Type.String()), ttl_hours: Type.Optional(Type.Number()) }) }), M.OrganizationInvitationSchema, 'json'),
  acceptOrganizationInvitation: endpoint('POST', '/v1/organizations/:orgId/invitations/:invitationId/accept', Type.Object({ params: Type.Object({ orgId: Type.String(), invitationId: Type.String() }), body: Type.Object({ token: Type.String() }) }), M.AcceptedOrganizationInvitationSchema, 'json'),
  revokeOrganizationInvitation: endpoint('DELETE', '/v1/organizations/:orgId/invitations/:invitationId', Type.Object({ params: Type.Object({ orgId: Type.String(), invitationId: Type.String() }) }), M.RevokedOrganizationInvitationSchema, 'json'),
  getOrganizationJitSettings: endpoint('GET', '/v1/organizations/:orgId/jit', Type.Object({ params: Type.Object({ orgId: Type.String() }) }), M.OrganizationJitSettingsSchema, 'json'),
  updateOrganizationJitSettings: endpoint('PUT', '/v1/organizations/:orgId/jit', Type.Object({ params: Type.Object({ orgId: Type.String() }), body: M.OrganizationJitSettingsSchema }), M.OrganizationJitSettingsSchema, 'json'),
  listOrganizationApplications: endpoint('GET', '/v1/organizations/:orgId/applications', Type.Object({ params: Type.Object({ orgId: Type.String() }) }), M.ListResponseSchema(M.OrganizationApplicationSchema), 'json'),
  bindOrganizationApplication: endpoint('PUT', '/v1/organizations/:orgId/applications/:appId', Type.Object({ params: Type.Object({ orgId: Type.String(), appId: Type.String() }), body: Type.Optional(Type.Object({})) }), M.OrganizationApplicationSchema, 'json'),
  removeOrganizationApplication: endpoint('DELETE', '/v1/organizations/:orgId/applications/:appId', Type.Object({ params: Type.Object({ orgId: Type.String(), appId: Type.String() }) }), M.RemovedOrganizationApplicationSchema, 'json'),
  getOrganizationBranding: endpoint('GET', '/v1/organizations/:orgId/branding', Type.Object({ params: Type.Object({ orgId: Type.String() }) }), M.OrganizationBrandingSchema, 'json'),
  updateOrganizationBranding: endpoint('PUT', '/v1/organizations/:orgId/branding', Type.Object({ params: Type.Object({ orgId: Type.String() }), body: M.OrganizationBrandingSchema }), M.OrganizationBrandingSchema, 'json'),
  listRoles: endpoint('GET', '/v1/roles', Type.Object({  }), M.ListResponseSchema(M.WireRoleSchema), 'json'),
  createRole: endpoint('POST', '/v1/roles', Type.Object({ body: M.CreateRoleInputSchema }), M.WireRoleSchema, 'json'),
  getRole: endpoint('GET', '/v1/roles/:roleId', Type.Object({ params: Type.Object({ roleId: Type.String() }) }), M.WireRoleSchema, 'json'),
  updateRole: endpoint('PUT', '/v1/roles/:roleId', Type.Object({ params: Type.Object({ roleId: Type.String() }), body: M.UpdateRoleInputSchema }), M.WireRoleSchema, 'json'),
  deleteRole: endpoint('DELETE', '/v1/roles/:roleId', Type.Object({ params: Type.Object({ roleId: Type.String() }) }), Type.Void(), 'void'),
  listRolePermissions: endpoint('GET', '/v1/roles/:roleId/permissions', Type.Object({ params: Type.Object({ roleId: Type.String() }) }), M.ListResponseSchema(M.WirePermissionSchema), 'json'),
  createRolePermission: endpoint('POST', '/v1/roles/:roleId/permissions', Type.Object({ params: Type.Object({ roleId: Type.String() }), body: Type.Object({ name: Type.String(), description: Type.Optional(Type.String()), scope_id: Type.Optional(Type.String()) }) }), M.WirePermissionSchema, 'json'),
  deleteRolePermission: endpoint('DELETE', '/v1/roles/:roleId/permissions/:permissionId', Type.Object({ params: Type.Object({ roleId: Type.String(), permissionId: Type.String() }) }), Type.Void(), 'void'),
  assignRole: endpoint('POST', '/v1/roles/:roleId/assign', Type.Object({ params: Type.Object({ roleId: Type.String() }), body: Type.Object({ user_id: Type.Optional(Type.String()), organization_id: Type.Optional(Type.String()), application_id: Type.Optional(Type.String()) }) }), M.RoleAssignmentSchema, 'json'),
  listRoleAssignments: endpoint('GET', '/v1/roles/:roleId/assign', Type.Object({ params: Type.Object({ roleId: Type.String() }) }), M.ListResponseSchema(M.RoleAssignmentSchema), 'json'),
  revokeRole: endpoint('DELETE', '/v1/roles/:roleId/assign/:assignmentId', Type.Object({ params: Type.Object({ roleId: Type.String(), assignmentId: Type.String() }) }), Type.Void(), 'void'),
  getOrgRoleAssignments: endpoint('GET', '/v1/organizations/:orgId/roles', Type.Object({ params: Type.Object({ orgId: Type.String() }) }), M.ListResponseSchema(M.RoleAssignmentSchema), 'json'),
  getSignInExperience: endpoint('GET', '/v1/sign-in-experience', Type.Object({  }), SignInExperienceSchema, 'json'),
  resolveSignInExperience: endpoint('GET', '/v1/sign-in-experience/resolve', Type.Object({ query: Type.Optional(Type.Object({ application_id: Type.Optional(Type.String()) })) }), EffectiveSignInExperienceSchema, 'json'),
  resolvePublicSignInExperience: endpoint('GET', '/v1/public/sign-in-experience/resolve', Type.Object({ query: Type.Optional(Type.Object({ application_id: Type.Optional(Type.String()), authorization_id: Type.Optional(Type.String()) })) }), PublicEffectiveSignInExperienceSchema, 'json'),
  getPublicPhrases: endpoint('GET', '/v1/public/phrases/:languageTag', Type.Object({ params: Type.Object({ languageTag: Type.String() }) }), PublicPhraseBundleSchema, 'json'),
  updateSignInExperience: endpoint('PUT', '/v1/sign-in-experience', Type.Object({ body: M.SignInExperienceInputSchema }), SignInExperienceSchema, 'json'),
  getAuthConfig: endpoint('GET', '/v1/auth-config', Type.Object({  }), M.AuthConfigResponseSchema, 'json'),
  updateAuthConfig: endpoint('PATCH', '/v1/auth-config', Type.Object({ body: Type.Partial(M.AuthConfigResponseSchema) }), M.AuthConfigResponseSchema, 'json'),
  getCompatibilityReport: endpoint('GET', '/v1/compatibility/supabase', Type.Object({  }), Type.Object({ checks: Type.Array(CompatibilityCheckResultSchema), total: Type.Number(), passed: Type.Number() }), 'json'),
  listTenantConfigs: endpoint('GET', '/v1/tenant-config', Type.Object({ query: Type.Optional(Type.Object({ type: Type.Optional(Type.String()) })) }), M.ListResponseSchema(M.TenantConfigSchema), 'json'),
  getTenantConfig: endpoint('GET', '/v1/tenant-config/:type/:key', Type.Object({ params: Type.Object({ type: Type.String(), key: Type.String() }) }), M.TenantConfigSchema, 'json'),
  upsertTenantConfig: endpoint('PUT', '/v1/tenant-config/:type/:key', M.TenantConfigInputSchema, M.TenantConfigSchema, 'json'),
  deleteTenantConfig: endpoint('DELETE', '/v1/tenant-config/:type/:key', Type.Object({ params: Type.Object({ type: Type.String(), key: Type.String() }) }), M.TenantConfigSchema, 'json'),
  checkTenantDomain: endpoint('POST', '/v1/tenant-config/domain/:domain/check', Type.Object({ params: Type.Object({ domain: Type.String() }) }), M.DomainCheckSchema, 'json'),
  getAuthHookRegistrationGuide: endpoint('GET', '/v1/auth-hooks/registration-guide', Type.Object({  }), M.AuthHookRegistrationGuideSchema, 'json'),
  getAuthHookStatus: endpoint('GET', '/v1/auth-hooks/custom-access-token/status', Type.Object({  }), M.AuthHookStatusSchema, 'json'),
  verifyAuthHook: endpoint('POST', '/v1/auth-hooks/custom-access-token/verify', Type.Object({  }), M.AuthHookStatusSchema, 'json'),
  getBeforeUserCreatedHookStatus: endpoint('GET', '/v1/auth-hooks/before-user-created/status', Type.Object({  }), M.AuthHookStatusSchema, 'json'),
  verifyBeforeUserCreatedHook: endpoint('POST', '/v1/auth-hooks/before-user-created/verify', Type.Object({  }), M.AuthHookStatusSchema, 'json'),
  listTenantMembers: endpoint('GET', '/v1/tenant/members', Type.Object({ query: Type.Optional(Type.Object({ page: Type.Optional(Type.Number()), limit: Type.Optional(Type.Number()), search: Type.Optional(Type.String()) })) }), M.ListResponseSchema(M.TenantMemberSchema), 'json'),
  updateTenantMember: endpoint('PATCH', '/v1/tenant/members/:memberId', Type.Object({ params: Type.Object({ memberId: Type.String() }), body: M.UpdateTenantMemberInputSchema }), M.TenantMemberSchema, 'json'),
  removeTenantMember: { ...endpoint('DELETE', '/v1/tenant/members/:memberId', Type.Object({ params: Type.Object({ memberId: Type.String() }) }), Type.Void(), 'void'), wireResult: M.RemovedTenantMemberSchema },
  listTenantInvitations: endpoint('GET', '/v1/tenant/invitations', Type.Object({ query: Type.Optional(Type.Object({ page: Type.Optional(Type.Number()), limit: Type.Optional(Type.Number()), status: Type.Optional(Type.String()) })) }), M.ListResponseSchema(M.TenantInvitationSchema), 'json'),
  createTenantInvitation: endpoint('POST', '/v1/tenant/invitations', Type.Object({ body: M.CreateTenantInvitationInputSchema }), M.TenantInvitationSchema, 'json'),
  listWebhooks: endpoint('GET', '/v1/webhooks', Type.Object({  }), M.ListResponseSchema(M.WireWebhookSchema), 'json'),
  createWebhook: endpoint('POST', '/v1/webhooks', Type.Object({ body: Type.Object({ url: Type.String(), events: Type.Array(Type.String()), enabled: Type.Optional(Type.Boolean()) }) }), M.WireWebhookSchema, 'json'),
  getWebhook: endpoint('GET', '/v1/webhooks/:webhookId', Type.Object({ params: Type.Object({ webhookId: Type.String() }) }), M.WireWebhookSchema, 'json'),
  updateWebhook: endpoint('PUT', '/v1/webhooks/:webhookId', Type.Object({ params: Type.Object({ webhookId: Type.String() }), body: Type.Partial(Type.Object({ url: Type.String(), events: Type.Array(Type.String()), enabled: Type.Boolean() })) }), M.WireWebhookSchema, 'json'),
  deleteWebhook: endpoint('DELETE', '/v1/webhooks/:webhookId', Type.Object({ params: Type.Object({ webhookId: Type.String() }) }), Type.Void(), 'void'),
  rotateWebhookSecret: endpoint('POST', '/v1/webhooks/:webhookId/rotate-secret', Type.Object({ params: Type.Object({ webhookId: Type.String() }) }), M.WireWebhookSchema, 'json'),
  listWebhookLogs: endpoint('GET', '/v1/webhooks/:webhookId/logs', Type.Object({ params: Type.Object({ webhookId: Type.String() }), query: Type.Optional(Type.Object({ limit: Type.Optional(Type.Number()) })) }), M.CursorListResponseSchema(M.WebhookDeliveryLogSchema), 'json'),
  testWebhook: endpoint('POST', '/v1/webhooks/:webhookId/test', Type.Object({ params: Type.Object({ webhookId: Type.String() }), body: Type.Optional(Type.Object({})) }), M.WebhookQueuedSchema, 'json'),
  listWebhookEvents: endpoint('GET', '/v1/webhooks/events', Type.Object({  }), M.WebhookEventListSchema, 'json'),
  listWebhookDeliveries: endpoint('GET', '/v1/webhooks/:webhookId/deliveries', Type.Object({ params: Type.Object({ webhookId: Type.String() }), query: Type.Optional(Type.Object({ limit: Type.Optional(Type.Number()), cursor: Type.Optional(Type.String()), status: Type.Optional(Type.String()) })) }), M.CursorListResponseSchema(M.WebhookDeliveryLogSchema), 'json'),
  getWebhookDelivery: endpoint('GET', '/v1/webhooks/:webhookId/deliveries/:deliveryId', Type.Object({ params: Type.Object({ webhookId: Type.String(), deliveryId: Type.String() }) }), M.WebhookDeliveryLogSchema, 'json'),
  replayWebhookDelivery: endpoint('POST', '/v1/webhooks/:webhookId/deliveries/:deliveryId/replay', Type.Object({ params: Type.Object({ webhookId: Type.String(), deliveryId: Type.String() }) }), M.WebhookReplaySchema, 'json'),
  syncUserMetadata: endpoint('POST', '/v1/sync/user/:userId', Type.Object({ params: Type.Object({ userId: Type.String() }), query: Type.Optional(Type.Object({ org_id: Type.Optional(Type.String()) })) }), M.SyncResultSchema, 'json'),
  syncOrgMetadata: endpoint('POST', '/v1/sync/org/:orgId', Type.Object({ params: Type.Object({ orgId: Type.String() }) }), Type.Object({ results: Type.Array(M.SyncResultSchema), total: Type.Number(), failed: Type.Number() }), 'json'),
  listAuditLogs: endpoint('GET', '/v1/audit', Type.Object({ query: Type.Optional(Type.Object({ event_type: Type.Optional(Type.String()), resource_type: Type.Optional(Type.String()), resource_id: Type.Optional(Type.String()), actor_id: Type.Optional(Type.String()), status: Type.Optional(Type.Number()), method: Type.Optional(Type.String()), limit: Type.Optional(Type.Number()), offset: Type.Optional(Type.Number()), from: Type.Optional(Type.String()), to: Type.Optional(Type.String()), cursor: Type.Optional(Type.String()) })) }), M.CursorListResponseSchema(M.WireAuditLogEntrySchema), 'json'),
  getAuditLog: endpoint('GET', '/v1/audit/:logId', Type.Object({ params: Type.Object({ logId: Type.String() }) }), M.WireAuditLogEntrySchema, 'json'),
  createAuditExport: endpoint('POST', '/v1/audit/export', Type.Object({ body: M.AuditExportInputSchema }), M.AuditExportSchema, 'json'),
  getAuditExport: endpoint('GET', '/v1/audit/export/:exportId', Type.Object({ params: Type.Object({ exportId: Type.String() }) }), M.AuditExportSchema, 'json'),
  getAuditExportDownload: endpoint('GET', '/v1/audit/export/:exportId/download', Type.Object({ params: Type.Object({ exportId: Type.String() }) }), Type.String({ format: 'binary' }), 'blob'),
  getAuditIntegrity: endpoint('GET', '/v1/audit/integrity', Type.Object({  }), M.AuditIntegritySchema, 'json'),
  compileAuthorizationPlan: endpoint('POST', '/v1/admin-tools/authorization-compiler', Type.Object({ body: M.AuthorizationCompileRequestSchema }), M.AuthorizationCompileResultSchema, 'json'),
  getAuthorizationCompilerDemo: endpoint('GET', '/v1/admin-tools/authorization-compiler/demo', Type.Object({  }), M.AuthorizationCompileResultSchema, 'json'),
  generateRLSMigration: endpoint('POST', '/v1/admin-tools/rls-migration', Type.Object({ body: Type.Object({ policies: Type.Array(M.ExistingPolicySchema) }) }), M.MigrationResultSchema, 'json'),
  getRLSMigrationDemo: endpoint('GET', '/v1/admin-tools/rls-migration/demo', Type.Object({  }), M.MigrationResultSchema, 'json'),
  listOrgTemplates: endpoint('GET', '/v1/org-templates', Type.Object({  }), M.ListResponseSchema(M.OrganizationTemplateSchema), 'json'),
  createOrgTemplate: endpoint('POST', '/v1/org-templates', Type.Object({ body: Type.Object({ name: Type.String(), description: Type.Optional(Type.String()), template_roles: Type.Optional(Type.Array(Type.Object({ name: Type.String(), permissions: Type.Array(Type.String()) }))), template_scopes: Type.Optional(Type.Array(Type.Object({ name: Type.String(), description: Type.Optional(Type.String()) }))), is_default: Type.Optional(Type.Boolean()) }) }), M.OrganizationTemplateSchema, 'json'),
  instantiateOrgTemplate: endpoint('POST', '/v1/org-templates/:templateId/instantiate', Type.Object({ params: Type.Object({ templateId: Type.String() }), body: Type.Object({ name: Type.String(), description: Type.Optional(Type.String()), creator_user_id: Type.String() }), headers: Type.Object({ 'Idempotency-Key': Type.String({ minLength: 1 }) }) }), M.InstantiatedOrganizationSchema, 'json'),
  getSecurityStatus: endpoint('GET', '/v1/security-config/status', Type.Object({  }), M.SecurityStatusSchema, 'json'),
  getProvisioningStatus: endpoint('GET', '/v1/provisioning/:projectRef', Type.Object({ params: Type.Object({ projectRef: Type.String() }) }), M.ProvisioningStatusSchema, 'json'),
  reconcileProject: endpoint('POST', '/v1/provisioning/:projectRef/reconcile', Type.Object({ params: Type.Object({ projectRef: Type.String() }) }), M.ProvisioningReconcileSchema, 'json'),
  listEnterpriseSSOConfigs: endpoint('GET', '/v1/enterprise-sso', Type.Object({  }), M.ListResponseSchema(M.EnterpriseSSOConfigSchema), 'json'),
  createEnterpriseSSOConfig: endpoint('POST', '/v1/enterprise-sso', Type.Object({ body: Type.Object({ connector_id: Type.String(), domains: Type.Array(Type.String()), sso_protocol: Type.Optional(Type.String()), jit_provisioning: Type.Optional(Type.Union([Type.Boolean(), Type.Null()])), org_membership_mapping: Type.Optional(Type.Union([Type.Record(StringKeySchema, Type.String()), Type.Null()])), role_mapping: Type.Optional(Type.Union([Type.Record(StringKeySchema, Type.String()), Type.Null()])) }) }), M.EnterpriseSSOConfigSchema, 'json'),
} as const;
export type SdkEndpointName = keyof typeof sdkEndpoints;
export type SdkEndpointInput<K extends SdkEndpointName> = Static<(typeof sdkEndpoints)[K]['input']>;
export type SdkEndpointResult<K extends SdkEndpointName> = Static<(typeof sdkEndpoints)[K]['result']>;
