#!/usr/bin/env bun

import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { renderHostedPage } from '../packages/admin-console/src/hosted/build.js';

const root = resolve(new URL('..', import.meta.url).pathname);
const output = resolve(root, 'packages/auth-server/src/generated/hosted-pages.ts');
const hostedSessionClient = resolve(root, 'packages/admin-console/src/hosted/session-client.ts');
const authorizeHtml = await renderHostedPage('authorize');
const claimHtml = await renderHostedPage('claim');
const changePasswordHtml = await renderHostedPage('change-password');
const accountHtml = await renderHostedPage('account');
const logoutHtml = await renderHostedPage('logout');
const hostedSessionBuild = await Bun.build({
  entrypoints: [hostedSessionClient],
  target: 'browser',
  format: 'iife',
  minify: true,
  sourcemap: 'none',
});

if (!hostedSessionBuild.success || hostedSessionBuild.outputs.length !== 1) {
  const buildErrors = hostedSessionBuild.logs.map((log) => log.message).join('\n');
  throw new Error(`Failed to build hosted session client${buildErrors ? `:\n${buildErrors}` : ''}`);
}

const hostedSessionOutput = hostedSessionBuild.outputs[0];
if (!hostedSessionOutput) throw new Error('Hosted session build output is missing');
const hostedSessionJs = await hostedSessionOutput.text();

mkdirSync(dirname(output), { recursive: true });
writeFileSync(
  output,
  [
    '// Generated by scripts/generate-hosted-pages.ts.',
    'export const EMBEDDED_HOSTED_SESSION_JS = ' + JSON.stringify(hostedSessionJs) + ';',
    'export const EMBEDDED_AUTHORIZE_HTML = ' + JSON.stringify(authorizeHtml) + ';',
    'export const EMBEDDED_CLAIM_HTML = ' + JSON.stringify(claimHtml) + ';',
    'export const EMBEDDED_CHANGE_PASSWORD_HTML = ' + JSON.stringify(changePasswordHtml) + ';',
    'export const EMBEDDED_ACCOUNT_HTML = ' + JSON.stringify(accountHtml) + ';',
    'export const EMBEDDED_LOGOUT_HTML = ' + JSON.stringify(logoutHtml) + ';',
    '',
  ].join('\n'),
);

console.log('Generated packages/auth-server/src/generated/hosted-pages.ts');
