#!/usr/bin/env bun

import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';

const root = resolve(new URL('..', import.meta.url).pathname);
const output = resolve(root, 'packages/auth-server/src/generated/hosted-pages.ts');
const authorizeHtml = readFileSync(resolve(root, 'packages/admin-console/static/authorize.html'), 'utf8');
const claimHtml = readFileSync(resolve(root, 'packages/admin-console/static/claim.html'), 'utf8');
const changePasswordHtml = readFileSync(resolve(root, 'packages/admin-console/static/change-password.html'), 'utf8');
const accountHtml = readFileSync(resolve(root, 'packages/admin-console/static/account.html'), 'utf8');

mkdirSync(dirname(output), { recursive: true });
writeFileSync(
  output,
  [
    '// Generated by scripts/generate-hosted-pages.ts.',
    'export const EMBEDDED_AUTHORIZE_HTML = ' + JSON.stringify(authorizeHtml) + ';',
    'export const EMBEDDED_CLAIM_HTML = ' + JSON.stringify(claimHtml) + ';',
    'export const EMBEDDED_CHANGE_PASSWORD_HTML = ' + JSON.stringify(changePasswordHtml) + ';',
    'export const EMBEDDED_ACCOUNT_HTML = ' + JSON.stringify(accountHtml) + ';',
    '',
  ].join('\n'),
);

console.log('Generated packages/auth-server/src/generated/hosted-pages.ts');
