#!/usr/bin/env bun

import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';

const root = resolve(new URL('..', import.meta.url).pathname);
const output = resolve(root, 'packages/auth-server/src/generated/hosted-pages.ts');
const hostedSessionClient = resolve(root, 'packages/admin-console/src/hosted/session-client.ts');
const authorizeHtml = readFileSync(resolve(root, 'packages/admin-console/static/authorize.html'), 'utf8');
const claimHtml = readFileSync(resolve(root, 'packages/admin-console/static/claim.html'), 'utf8');
const changePasswordHtml = readFileSync(resolve(root, 'packages/admin-console/static/change-password.html'), 'utf8');
const accountHtml = readFileSync(resolve(root, 'packages/admin-console/static/account.html'), 'utf8');
const hostedSessionBuild = await Bun.build({
  entrypoints: [hostedSessionClient],
  target: 'browser',
  format: 'iife',
  minify: true,
  sourcemap: 'none',
});

if (!hostedSessionBuild.success || hostedSessionBuild.outputs.length !== 1) {
  const buildErrors = hostedSessionBuild.logs.map((log) => log.message).join('\n');
  throw new Error(`Failed to build hosted session client${buildErrors ? `:\n${buildErrors}` : ''}`);
}

const hostedSessionJs = await hostedSessionBuild.outputs[0].text();

mkdirSync(dirname(output), { recursive: true });
writeFileSync(
  output,
  [
    '// Generated by scripts/generate-hosted-pages.ts.',
    'export const EMBEDDED_HOSTED_SESSION_JS = ' + JSON.stringify(hostedSessionJs) + ';',
    'export const EMBEDDED_AUTHORIZE_HTML = ' + JSON.stringify(authorizeHtml) + ';',
    'export const EMBEDDED_CLAIM_HTML = ' + JSON.stringify(claimHtml) + ';',
    'export const EMBEDDED_CHANGE_PASSWORD_HTML = ' + JSON.stringify(changePasswordHtml) + ';',
    'export const EMBEDDED_ACCOUNT_HTML = ' + JSON.stringify(accountHtml) + ';',
    '',
  ].join('\n'),
);

console.log('Generated packages/auth-server/src/generated/hosted-pages.ts');
